/**
 * Seed product list for bulk import to Firestore.
 * Used by Admin panel "Import seed products" — adds only if product id doesn't exist.
 * Unit: ק"ג = perKg, יחידה = perUnit.
 */
export const SEED_PRODUCTS = [
  { he: "עגבנייה", en: "Tomato", unit: "perKg", price: 17.9, cat: "vegetables", img: "🍅" },
  { he: "מלפפון", en: "Cucumber", unit: "perKg", price: 13.9, cat: "vegetables", img: "🥒" },
  { he: "פלפל גמבה", en: "Bell pepper", unit: "perKg", price: 18.9, cat: "vegetables", img: "🫑" },
  { he: "שושקה", en: "Shoshka tomato", unit: "perKg", price: 29.9, cat: "vegetables", img: "🍅" },
  { he: "חריף", en: "Hot pepper", unit: "perKg", price: 19.9, cat: "vegetables", img: "🌶️" },
  { he: "חציל", en: "Eggplant", unit: "perKg", price: 15.9, cat: "vegetables", img: "🍆" },
  { he: "זוקיני", en: "Zucchini", unit: "perKg", price: 19.9, cat: "vegetables", img: "🥒" },
  { he: "קישוא", en: "Courgette", unit: "perKg", price: 16.9, cat: "vegetables", img: "🥒" },
  { he: "תפוז", en: "Orange", unit: "perKg", price: 14.9, cat: "fruits", img: "🍊" },
  { he: "אטינגר", en: "Etringer", unit: "perKg", price: 19.9, cat: "fruits", img: "🍐" },
  { he: "האס", en: "Hass avocado", unit: "perKg", price: 23.9, cat: "fruits", img: "🥑" },
  { he: "לימון", en: "Lemon", unit: "perKg", price: 19.9, cat: "fruits", img: "🍋" },
  { he: "צנון", en: "Radish", unit: "perKg", price: 14.9, cat: "vegetables", img: "🥬" },
  { he: "קולורבי", en: "Kohlrabi", unit: "perKg", price: 14.9, cat: "vegetables", img: "🥬" },
  { he: "סלק", en: "Beet", unit: "perKg", price: 9.9, cat: "vegetables", img: "🫒" },
  { he: "בצל יבש", en: "Dry onion", unit: "perKg", price: 9.9, cat: "vegetables", img: "🧅" },
  { he: "בטטה רגילה/צבעונית", en: "Sweet potato", unit: "perKg", price: 19.9, cat: "vegetables", img: "🍠" },
  { he: "גורמה", en: "Gourmet potato", unit: "perKg", price: 13.9, cat: "vegetables", img: "🥔" },
  { he: "תפוא תפזורת", en: "Potato loose", unit: "perKg", price: 9.9, cat: "vegetables", img: "🥔" },
  { he: "באטר", en: "Butter potato", unit: "perKg", price: 11.9, cat: "vegetables", img: "🥔" },
  { he: "מגי", en: "Mango", unit: "perKg", price: 29.9, cat: "fruits", img: "🥭" },
  { he: "קלמנטינה", en: "Clementine", unit: "perKg", price: 18.9, cat: "fruits", img: "🍊" },
  { he: "תפוח עץ", en: "Apple", unit: "perKg", price: 18.9, cat: "fruits", img: "🍎" },
  { he: "פינק", en: "Pink lady apple", unit: "perKg", price: 23.9, cat: "fruits", img: "🍎" },
  { he: "דלוריה", en: "Deloria", unit: "perKg", price: 12.9, cat: "vegetables", img: "🥔" },
  { he: "דלעת ערמונים", en: "Chestnut pumpkin", unit: "perUnit", price: 19.9, cat: "vegetables", img: "🎃" },
  { he: "ספגטיי", en: "Spaghetti squash", unit: "perUnit", price: 24.9, cat: "vegetables", img: "🎃" },
  { he: "יפנית", en: "Japanese squash", unit: "perUnit", price: 15.9, cat: "vegetables", img: "🎃" },
  { he: "מלון", en: "Melon", unit: "perKg", price: 15.9, cat: "fruits", img: "🍈" },
  { he: "פומלה", en: "Pomelo", unit: "perKg", price: 14.9, cat: "fruits", img: "🍊" },
  { he: "אשכולית אדומה", en: "Red grapefruit", unit: "perKg", price: 14.9, cat: "fruits", img: "🍊" },
  { he: "פומלית", en: "Sweetie", unit: "perKg", price: 9.9, cat: "fruits", img: "🍊" },
  { he: "בננה", en: "Banana", unit: "perKg", price: 14.9, cat: "fruits", img: "🍌" },
  { he: "אבטיח", en: "Watermelon", unit: "perKg", price: 12.9, cat: "fruits", img: "🍉" },
  { he: "שרי", en: "Cherry", unit: "perKg", price: 34.9, cat: "fruits", img: "🍒" },
  { he: "אפרסמון", en: "Persimmon", unit: "perKg", price: 34.9, cat: "fruits", img: "🍅" },
  { he: "אגס", en: "Pear", unit: "perKg", price: 29.9, cat: "fruits", img: "🍐" },
  { he: "קיווי ירוק", en: "Green kiwi", unit: "perKg", price: 34.9, cat: "fruits", img: "🥝" },
  { he: "צהוב", en: "Yellow kiwi", unit: "perKg", price: 46.9, cat: "fruits", img: "🥝" },
  { he: "פפאיה", en: "Papaya", unit: "perKg", price: 34.9, cat: "fruits", img: "🍈" },
  { he: "רימון", en: "Pomegranate", unit: "perKg", price: 23.9, cat: "fruits", img: "🍎" },
  { he: "שום תפזורת", en: "Garlic loose", unit: "perKg", price: 29.9, cat: "vegetables", img: "🧄" },
  { he: "תפוז ברשת", en: "Orange in mesh", unit: "perKg", price: 9.9, cat: "fruits", img: "🍊" },
  { he: "שום ארוז", en: "Garlic packed", unit: "perUnit", price: 10.5, cat: "vegetables", img: "🧄" },
  { he: "תמר מגהול", en: "Medjool date", unit: "perUnit", price: 25.9, cat: "fruits", img: "🌴" },
  { he: "תות", en: "Strawberry", unit: "perUnit", price: 30, cat: "fruits", img: "🍓" },
  { he: "פומלה קלופה", en: "Peeled pomelo", unit: "perUnit", price: 22, cat: "fruits", img: "🍊" },
  { he: "תמר ממולא", en: "Stuffed date", unit: "perUnit", price: 35, cat: "fruits", img: "🌴" },
  { he: "כרוב", en: "Cabbage", unit: "perKg", price: 10.9, cat: "vegetables", img: "🥬" },
  { he: "גזר", en: "Carrot", unit: "perKg", price: 10.9, cat: "vegetables", img: "🥕" },
  { he: "ארטישוק", en: "Artichoke", unit: "perKg", price: 29.9, cat: "vegetables", img: "🥬" },
  { he: "כריש", en: "Leek", unit: "perUnit", price: 11.9, cat: "vegetables", img: "🧅" },
  { he: "נענע", en: "Mint", unit: "perUnit", price: 4, cat: "herbs", img: "🌿" },
  { he: "שמיר", en: "Dill", unit: "perUnit", price: 4, cat: "herbs", img: "🌿" },
  { he: "פטרוזיליה", en: "Parsley", unit: "perUnit", price: 4, cat: "herbs", img: "🌿" },
  { he: "כוסברה", en: "Cilantro", unit: "perUnit", price: 4, cat: "herbs", img: "🌿" },
  { he: "כרובית", en: "Cauliflower", unit: "perUnit", price: 16, cat: "vegetables", img: "🥦" },
  { he: "ברוקולי", en: "Broccoli", unit: "perUnit", price: 15, cat: "vegetables", img: "🥦" },
  { he: "מנגולד", en: "Chard", unit: "perUnit", price: 10, cat: "vegetables", img: "🥬" },
  { he: "בצל ירוק", en: "Green onion", unit: "perUnit", price: 10, cat: "vegetables", img: "🧅" },
  { he: "שמפניון/פורטובלו", en: "Mushroom", unit: "perUnit", price: 15, cat: "vegetables", img: "🍄" },
  { he: "מלפפון/פלפל בייבי", en: "Baby cucumber/pepper", unit: "perUnit", price: 12, cat: "vegetables", img: "🥒" },
  { he: "צנונית", en: "Daikon", unit: "perUnit", price: 10, cat: "vegetables", img: "🥬" },
  { he: "שום קלוף", en: "Peeled garlic", unit: "perUnit", price: 12.9, cat: "vegetables", img: "🧄" },
  { he: "שורש סלרי נקי", en: "Celery root clean", unit: "perUnit", price: 14.9, cat: "vegetables", img: "🥬" },
  { he: "ראש סלרי", en: "Celery head", unit: "perUnit", price: 10, cat: "vegetables", img: "🥬" },
  { he: "שורש פטרוזיליה", en: "Parsley root", unit: "perUnit", price: 11.9, cat: "vegetables", img: "🥬" },
  { he: "סלרי עלים", en: "Celery leaves", unit: "perUnit", price: 10, cat: "vegetables", img: "🥬" },
  { he: "דלעת", en: "Pumpkin", unit: "perKg", price: 14.9, cat: "vegetables", img: "🎃" },
  { he: "אפונת שלג", en: "Snow pea", unit: "perUnit", price: 24.9, cat: "vegetables", img: "🥬" },
  { he: "ארטישוק ירושלמי", en: "Jerusalem artichoke", unit: "perUnit", price: 21.9, cat: "vegetables", img: "🥔" },
  { he: "תרד", en: "Spinach", unit: "perUnit", price: 15, cat: "vegetables", img: "🥬" },
  { he: "רוקולה", en: "Arugula", unit: "perUnit", price: 15, cat: "vegetables", img: "🥬" },
  { he: "סלנובה", en: "Salanova", unit: "perUnit", price: 16, cat: "vegetables", img: "🥬" },
  { he: "לאליק", en: "Lollo", unit: "perUnit", price: 16, cat: "vegetables", img: "🥬" },
  { he: "קיסר", en: "Caesar lettuce", unit: "perUnit", price: 15, cat: "vegetables", img: "🥬" },
  { he: "פלפל צ'ילי", en: "Chili pepper", unit: "perUnit", price: 12, cat: "vegetables", img: "🌶️" },
  { he: "תפוח אדמה למיקרו", en: "Microwave potato", unit: "perUnit", price: 12.9, cat: "vegetables", img: "🥔" },
  { he: "שורש כורכום", en: "Turmeric root", unit: "perUnit", price: 19.9, cat: "herbs", img: "🌿" },
  { he: "עירית", en: "Chive", unit: "perUnit", price: 10, cat: "herbs", img: "🌿" },
  { he: "בזיליקום", en: "Basil", unit: "perUnit", price: 10, cat: "herbs", img: "🌿" },
  { he: "טימן", en: "Thyme", unit: "perUnit", price: 10, cat: "herbs", img: "🌿" },
  { he: "מרווה", en: "Sage", unit: "perUnit", price: 10, cat: "herbs", img: "🌿" },
  { he: "רוזמרין", en: "Rosemary", unit: "perUnit", price: 10, cat: "herbs", img: "🌿" },
  { he: "אורגנו", en: "Oregano", unit: "perUnit", price: 10, cat: "herbs", img: "🌿" },
  { he: "אנדיביה", en: "Endive", unit: "perUnit", price: 23.9, cat: "vegetables", img: "🥬" },
  { he: "סלק וואקום", en: "Vacuum beet", unit: "perUnit", price: 10, cat: "vegetables", img: "🥬" },
  { he: "בצל שאלוט", en: "Shallot", unit: "perUnit", price: 12.9, cat: "vegetables", img: "🧅" },
];
